---
title: "LESP Chick Fledging"
author: "Sydney Collins"
date: "2023-06-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Load Packages and Data}
rm(list=ls())
options(scipen = 999)

#Libraries
library(tidyverse)
library(patchwork)
library(lubridate)
library(data.table)
library(doBy)
library(moonlit)
library(sjmisc)
library(tibble)

#Data frames
load("data/chick.Rda")
load("data/moon.Rda")
load("data/cloud.Rda")
load("data/moondates.Rda")
load("data/strand.Rda")
```

```{r Summary Stats}
#Histograms of date and time
suntimehist <- ggplot(chick, aes(x = TimeAfterSunset))+
  xlab("Hours After Sunset")+
  ylab("Number of Fledglings")+
  geom_histogram(colour = "black", fill = "lightgrey", binwidth = 1) +
  geom_vline(xintercept = median(chick$TimeAfterSunset), linewidth = 1.5, color = "black", linetype = "dashed")+
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), legend.position = "none")
suntimehist

timehist <- ggplot(chick, aes(x = ITime))+
  xlab("Minutes after 18:00")+
  ylab("Number of Fledglings")+
  geom_histogram(colour = "black", fill = "lightgrey", binwidth = 30)+
  geom_vline(xintercept = median(chick$ITime), linewidth = 1.5,colour = "black", linetype = "dashed")+
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), legend.position = "none")
timehist

datehist <- ggplot(chick, aes(x = yDate))+
  xlab("Day of Year")+
  ylab("Number of Fledglings")+
  geom_histogram(colour = "black", fill = "lightgrey", binwidth = 5)+
  geom_vline(xintercept = median(chick$yDate), linewidth = 1.5, color = "black", linetype = "dashed")+
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), legend.position = "none")
datehist

#Summary stats for date and time per year
results <- summaryBy(ITime + yDate + TimeAfterSunset ~ Year, FUN = c(length, mean, sd, median, IQR, min, max), data = chick)
results$Date.mean <- as.Date(results$yDate.mean, origin = "2021-01-01")
results$Date.median <- as.Date(results$yDate.median, origin = "2021-01-01")
results$Date.min <- as.Date(results$yDate.min, origin = "2021-01-01")
results$Date.max <- as.Date(results$yDate.max, origin = "2021-01-01")

#Summary stats for whole sample (use medians and IQR because the data are highly right-skewed)
median(chick$ITime)
IQR(chick$ITime)

median(chick$TimeAfterSunset)
IQR(chick$TimeAfterSunset)

as.Date(median(chick$yDate), origin = "2017-01-01")
IQR(chick$yDate)

###Figure 1####
jpeg(filename = "figures/Figure1_histograms.jpeg", units = "cm", res = 300, width = 15, height = 18)
suntimehist / datehist + plot_annotation(tag_levels = list(c("A", "B")))
dev.off()

#Figure S5####
jpeg(filename = "figures/FigureS5_time_hist.jpeg", units = "cm", res = 300, width = 15, height = 10)
timehist
dev.off()
```

```{r Annual Differences}
#Time - highly right skewed so use the non-parametric test
boxplot(TimeAfterSunset ~ Year, data = chick)
kruskal.test(TimeAfterSunset ~ Year, data = chick)

#Date - looks normal so use ANOVA
boxplot(yDate ~ Year, data = chick)
date_mod <- aov(yDate ~ Year, data = chick)
summary(date_mod)
TukeyHSD(date_mod)
```

```{r Moon Phase on Peak Fledge Day}
start_date17 <- as.POSIXct("2017-09-13")
dates17 <- as.data.frame(seq(start_date17, by = "day", length.out = 70)) %>%
  rename(DateTime = `seq(start_date17, by = "day", length.out = 70)`)
dates17 <- calculateMoonlightIntensity(lat = 47.26265, lon = -52.77187, date = dates17$DateTime, e = 0.26)
peak17 <- ggplot(data = dates17, aes(x = date, y = moonPhase*100)) +
  geom_point() +
  geom_vline(aes(xintercept = as.POSIXct("2017-10-11 00:00:00"))) +
  geom_vline(aes(xintercept = as.POSIXct("2017-10-10 00:00:00")), colour = "red") +
  xlab("Date") +
  ylab("Moon Phase") +
  ggtitle("2017") +
  theme_classic()

start_date18 <- as.POSIXct("2018-09-13")
dates18 <- as.data.frame(seq(start_date18, by = "day", length.out = 70)) %>%
  rename(DateTime = `seq(start_date18, by = "day", length.out = 70)`)
dates18 <- calculateMoonlightIntensity(lat = 47.26265, lon = -52.77187, date = dates18$DateTime, e = 0.26)
peak18 <- ggplot(data = dates18, aes(x = date, y = moonPhase*100)) +
  geom_point() +
  geom_vline(aes(xintercept = as.POSIXct("2018-10-8 00:00:00"))) +
  geom_vline(aes(xintercept = as.POSIXct("2018-10-10 00:00:00")), colour = "red") +
  xlab("Date") +
  ylab("Moon Phase") +
  ggtitle("2018") +
  theme_classic()

start_date21 <- as.POSIXct("2021-09-13")
dates21 <- as.data.frame(seq(start_date21, by = "day", length.out = 70)) %>%
  rename(DateTime = `seq(start_date21, by = "day", length.out = 70)`)
dates21 <- calculateMoonlightIntensity(lat = 47.26265, lon = -52.77187, date = dates21$DateTime, e = 0.26)
peak21 <- ggplot(data = dates21, aes(x = date, y = moonPhase*100)) +
  geom_point() +
  geom_vline(aes(xintercept = as.POSIXct("2021-09-29 00:00:00"))) +
  geom_vline(aes(xintercept = as.POSIXct("2021-10-10 00:00:00")), colour = "red") +
  xlab("Date") +
  ylab("Moon Phase") +
  ggtitle("2021") +
  theme_classic()

start_date22 <- as.POSIXct("2022-09-13")
dates22 <- as.data.frame(seq(start_date22, by = "day", length.out = 70)) %>%
  rename(DateTime = `seq(start_date22, by = "day", length.out = 70)`)
dates22 <- calculateMoonlightIntensity(lat = 47.26265, lon = -52.77187, date = dates22$DateTime, e = 0.26)
peak22 <- ggplot(data = dates22, aes(x = date, y = moonPhase*100)) +
  geom_point() +
  geom_vline(aes(xintercept = as.POSIXct("2022-10-11 00:00:00"))) +
  geom_vline(aes(xintercept = as.POSIXct("2022-10-10 00:00:00")), colour = "red") +
  xlab("Date") +
  ylab("Moon Phase") +
  ggtitle("2022") +
  theme_classic()

###Figure S6####
jpeg(filename = "figures/FigureS6_moon_peak.jpeg", units = "cm", res = 300, width = 15, height = 12)
peak17 + peak18 + peak21 + peak22
dev.off()
```

```{r Moon Phase KS Test}
ks.test(chick$moonPhase, moondates$moonPhase)

moon_phase_prop <- as.data.frame(table(moondates$phasecat)) %>%
  mutate(prop = Freq/nrow(moondates)) %>%
  mutate(Var1 = as.numeric(as.character(Var1))) %>%
  arrange(Var1) %>%
  mutate(Expected = prop*120)
chick_phase_prop <- as.data.frame(table(chick$phasecat)) %>%
  mutate(prop = Freq/nrow(chick)) %>%
  mutate(Var1 = as.numeric(as.character(Var1))) %>%
  add_row(Var1 = 30, Freq = 0, prop = 0) %>%
  arrange(Var1)

prop.test(x = chick_phase_prop[1,2], n = 120, p = moon_phase_prop[1,2]/nrow(moondates))
prop.test(x = chick_phase_prop[2,2], n = 120, p = moon_phase_prop[2,2]/nrow(moondates))
prop.test(x = chick_phase_prop[3,2], n = 120, p = moon_phase_prop[3,2]/nrow(moondates))
prop.test(x = chick_phase_prop[4,2], n = 120, p = moon_phase_prop[4,2]/nrow(moondates))
prop.test(x = chick_phase_prop[5,2], n = 120, p = moon_phase_prop[5,2]/nrow(moondates))
prop.test(x = chick_phase_prop[6,2], n = 120, p = moon_phase_prop[6,2]/nrow(moondates))
prop.test(x = chick_phase_prop[7,2], n = 120, p = moon_phase_prop[7,2]/nrow(moondates))
prop.test(x = chick_phase_prop[8,2], n = 120, p = moon_phase_prop[8,2]/nrow(moondates))
prop.test(x = chick_phase_prop[9,2], n = 120, p = moon_phase_prop[9,2]/nrow(moondates))
prop.test(x = chick_phase_prop[10,2], n = 120, p = moon_phase_prop[10,2]/nrow(moondates))
prop.test(x = chick_phase_prop[11,2], n = 120, p = moon_phase_prop[11,2]/nrow(moondates))
prop.test(x = chick_phase_prop[12,2], n = 120, p = moon_phase_prop[12,2]/nrow(moondates))
prop.test(x = chick_phase_prop[13,2], n = 120, p = moon_phase_prop[13,2]/nrow(moondates))
prop.test(x = chick_phase_prop[14,2], n = 120, p = moon_phase_prop[14,2]/nrow(moondates))
prop.test(x = chick_phase_prop[15,2], n = 120, p = moon_phase_prop[15,2]/nrow(moondates))
prop.test(x = chick_phase_prop[16,2], n = 120, p = moon_phase_prop[16,2]/nrow(moondates))
prop.test(x = chick_phase_prop[17,2], n = 120, p = moon_phase_prop[17,2]/nrow(moondates))
prop.test(x = chick_phase_prop[18,2], n = 120, p = moon_phase_prop[18,2]/nrow(moondates))
prop.test(x = chick_phase_prop[19,2], n = 120, p = moon_phase_prop[19,2]/nrow(moondates))
prop.test(x = chick_phase_prop[20,2], n = 120, p = moon_phase_prop[20,2]/nrow(moondates))
```

```{r Incident Moon Illumination KS Test}
ks.test(chick$moonlightModel, moondates$moonlightModel)

moon_III_prop <- as.data.frame(table(moondates$illumcat)) %>%
  mutate(prop = Freq/nrow(moondates)) %>%
  mutate(Var1 = as.numeric(as.character(Var1))) %>%
  arrange(Var1) %>%
  mutate(Expected = prop*120)
chick_III_prop <- as.data.frame(table(chick$illumcat)) %>%
  mutate(prop = Freq/nrow(chick)) %>%
  mutate(Var1 = as.numeric(as.character(Var1))) %>%
  add_row(Var1 = 25, Freq = 0, prop = 0) %>%
  add_row(Var1 = 40, Freq = 0, prop = 0) %>%
  add_row(Var1 = 45, Freq = 0, prop = 0) %>%
  add_row(Var1 = 50, Freq = 0, prop = 0) %>%
  add_row(Var1 = 55, Freq = 0, prop = 0) %>%
  add_row(Var1 = 60, Freq = 0, prop = 0) %>%
  add_row(Var1 = 65, Freq = 0, prop = 0) %>%
  arrange(Var1)
  
prop.test(x = chick_III_prop[1,2], n = 120, p = moon_III_prop[1,2]/nrow(moondates))
prop.test(x = chick_III_prop[2,2], n = 120, p = moon_III_prop[2,2]/nrow(moondates))
prop.test(x = chick_III_prop[3,2], n = 120, p = moon_III_prop[3,2]/nrow(moondates))
prop.test(x = chick_III_prop[4,2], n = 120, p = moon_III_prop[4,2]/nrow(moondates))
prop.test(x = chick_III_prop[5,2], n = 120, p = moon_III_prop[5,2]/nrow(moondates))
prop.test(x = chick_III_prop[6,2], n = 120, p = moon_III_prop[6,2]/nrow(moondates))
prop.test(x = chick_III_prop[7,2], n = 120, p = moon_III_prop[7,2]/nrow(moondates))
prop.test(x = chick_III_prop[8,2], n = 120, p = moon_III_prop[8,2]/nrow(moondates))
prop.test(x = chick_III_prop[9,2], n = 120, p = moon_III_prop[9,2]/nrow(moondates))
prop.test(x = chick_III_prop[10,2], n = 120, p = moon_III_prop[10,2]/nrow(moondates))
prop.test(x = chick_III_prop[11,2], n = 120, p = moon_III_prop[11,2]/nrow(moondates))
prop.test(x = chick_III_prop[12,2], n = 120, p = moon_III_prop[12,2]/nrow(moondates))
prop.test(x = chick_III_prop[13,2], n = 120, p = moon_III_prop[13,2]/nrow(moondates))
prop.test(x = chick_III_prop[14,2], n = 120, p = moon_III_prop[14,2]/nrow(moondates))
```

```{r Figure 2}
strand_phase_prop <- as.data.frame(table(strand$phasecat)) %>%
  mutate(prop = Freq/nrow(strand)) %>%
  mutate(Var1 = as.numeric(as.character(Var1))) %>%
  arrange(Var1)

phase_points <- ggplot() +
  xlab("Incident Moon Illumination Index") +
  ylab("Proportion of Chicks") +
  geom_point(data = moon_phase_prop, aes(x = Var1, y = prop), colour = "darkgrey", size = 1) +
  geom_point(data = chick_phase_prop, aes(x = Var1, y = prop), colour = "black", size = 1) +
  geom_point(data = strand_phase_prop, aes(x = Var1, y = prop), colour = "red", size = 1) +
  geom_smooth(data = moon_phase_prop, aes(x = Var1, y = prop), colour = "darkgrey", se = F) +
  geom_smooth(data = chick_phase_prop, aes(x = Var1, y = prop), colour = "black", se = F) +
  geom_smooth(data = strand_phase_prop, aes(x = Var1, y = prop), colour = "red", se = F) +
  theme_classic()
phase_points

III_points <- ggplot() +
  xlab("Moon Phase") +
  ylab("Proportion of Chicks") +
  geom_point(data = moon_III_prop, aes(x = Var1, y = prop), colour = "grey", size = 1) +
  geom_point(data = chick_III_prop, aes(x = Var1, y = prop), colour = "black", size = 1) +
  geom_smooth(data = moon_III_prop, aes(x = Var1, y = prop), colour = "grey", se = F) +
  geom_smooth(data = chick_III_prop, aes(x = Var1, y = prop), colour = "black", se = F) +
  theme_classic()
III_points

phase_points_hist <- ggplot() +
  geom_bar(data = moondates, aes(x = as.factor(phasecat), y = (..count..)/sum(..count..)), fill = NA, colour = "darkgrey") +
  geom_bar(data = chick, aes(x = as.factor(phasecat), y = (..count..)/sum(..count..)), colour = "black", fill = NA) +
  geom_smooth(data = strand_phase_prop, aes(x = Var1/5, y = prop), colour = "red", se = F) +
  theme_classic() +
  xlab("Moon Phase") +
  ylab("Proportion of Chicks")
phase_points_hist

phase_hist <- ggplot() +
  geom_bar(data = moondates, aes(x = as.factor(phasecat), y = (..count..)/sum(..count..)), fill = "lightgrey", colour = "darkgrey") +
  geom_bar(data = chick, aes(x = as.factor(phasecat), y = (..count..)/sum(..count..)), colour = "black", fill = NA) +
  geom_bar(data = strand, aes(x = as.factor(phasecat), y = (..count..)/sum(..count..)), colour = "red", fill = NA) +
  theme_classic() +
  xlab("Moon Phase") +
  ylab("Proportion of Chicks")
phase_hist

III_hist <- ggplot() +
  geom_bar(data = moondates, aes(x = as.factor(illumcat), y = (..count..)/sum(..count..)), fill = "lightgrey", colour = "darkgrey") +
  geom_bar(data = chick, aes(x = as.factor(illumcat), y = (..count..)/sum(..count..)), colour = "black", fill = NA) +
  theme_classic() +
  xlab("Incident Moon Illumination Index") +
  ylab("Proportion of Chicks") +
  ylim(0, 0.6)
III_hist

phase_hist / III_hist
phase_points / III_points

###Figure 2####
jpeg(filename = "figures/Figure2.jpeg", units = "cm", res = 300, width = 15, height = 18)
phase_points / III_points + plot_annotation(tag_levels = list(c("A", "B")))
dev.off()
```

```{r Fledge when Moon is Up or Down}
#Do chicks fledge when the moon is below the horizon?
summary(as.factor(chick$MoonUp))
summary(as.factor(moondates$MoonUp))

chisq.test(x = c(64/120, 56/120), p = c(72484/147577, 75093/147577)) #no difference between the proportion of chicks that fledge when the moon is below the horizon and those that fledge when the moon is above the horizon
    #i.e. chicks do not seem to intentionally fledge when the moon is not out yet

summary(as.factor(chick$MoonUp))
table(chick$MoonUp, chick$Phase)
table(moondates$MoonUp, moondates$Phase)
boxplot(chick$moonPhase ~ chick$MoonUp)
plot(moondates$moonAltDegrees ~ moondates$moonPhase) #the moon tends to be above the horizon more when it is more full

chisq.test(x = c(31/120, 9/120, 5/120, 19/120, 3/120, 35/120, 5/120, 13/120), p = c(51957/195912, 10494/195912, 20006/195912, 14043/195912, 10807/195912, 54194/195912, 14431/195912, 19980/195912))

prop.test(x = 31, n = 120, p = 51957/195912) #first quarter down
prop.test(x = 3, n = 120, p = 10807/195912) #first quarter up
prop.test(x = 9, n = 120, p = 10494/195912) #fourth quarter down
prop.test(x = 35, n = 120, p = 54194/195912) #fourth quarter up
```

```{r Cloud Cover & Moon Phase Chi-squared}
#Create a variable describing weather
chick_weather <- chick %>% mutate(CloudCat = ifelse(CloudCover < 50, "low", "high")) %>%
  mutate(LightEnv = ifelse(Phase == "first quarter" & CloudCat == "low", "low1", ifelse(Phase == "first quarter" & CloudCat == "high", "high1", ifelse(Phase == "second quarter" & CloudCat == "low", "low2", ifelse(Phase == "second quarter" & CloudCat == "high", "high2", ifelse(Phase == "third quarter" & CloudCat == "low", "low3", ifelse(Phase == "third quarter" & CloudCat == "high", "high3", ifelse(Phase == "fourth quarter" & CloudCat == "low", "low4", "high4")))))) ))

#Crop the data to just the date range
cloud_lesp_range <- left_join(cloud, moon, by = "Date") %>%
  drop_na(Moon_Illumination) %>%
  mutate(CloudCat = ifelse(CloudCover < 50, "low", "high")) %>%
  mutate(LightEnv = ifelse(Phase == "first quarter" & CloudCat == "low", "low1", ifelse(Phase == "first quarter" & CloudCat == "high", "high1", ifelse(Phase == "second quarter" & CloudCat == "low", "low2", ifelse(Phase == "second quarter" & CloudCat == "high", "high2", ifelse(Phase == "third quarter" & CloudCat == "low", "low3", ifelse(Phase == "third quarter" & CloudCat == "high", "high3", ifelse(Phase == "fourth quarter" & CloudCat == "low", "low4", "high4")))))))) %>%
  mutate(yDate = yday(Date)) %>%
  filter(yDate < 318) %>%
  filter(yDate > 255)

#Chi-squared test
fledge_prop2 <- summary(as.factor(chick_weather$LightEnv))
summary(as.factor(cloud_lesp_range$LightEnv))
chisq.test(x = fledge_prop2, p = c(73/372, 37/372, 42/372, 83/372, 40/372, 24/372, 21/372, 52/372))

#Post-hoc tests
prop.test(x = 19, n = 120, p = 73/372, alternative="two.sided") #high1
prop.test(x = 7, n = 120, p = 37/372, alternative="two.sided") #high2
prop.test(x = 20, n = 120, p = 42/372, alternative="two.sided") #high3
prop.test(x = 26, n = 120, p = 83/372, alternative="two.sided") #high4
prop.test(x = 15, n = 120, p = 40/372, alternative="two.sided") #low1
prop.test(x =3, n = 120, p = 24/372, alternative="two.sided") #low2
prop.test(x = 12, n = 120, p = 21/372, alternative="two.sided") #low3
prop.test(x = 18, n = 120, p = 52/372, alternative="two.sided") #low4

#Bar graph of moon x cloud cover
bartable <- as.data.frame(fledge_prop2)
names(bartable) <- c("value")
bartable$condition <- rownames(bartable)
bartable$type <- "Observed"
b <- as.data.frame(summary(as.factor(cloud_lesp_range$LightEnv))/372)*122
names(b) <- c("value")
b$condition <- rownames(b)
b$type <- "Expected"
bartable <- rbind(bartable, b)

####Figure S3####
jpeg(filename = "figures/FigureS3_CloudMoonChi.jpeg", units = "cm", res = 300, width = 15, height = 13)
ggplot(bartable) +
  geom_bar(aes(x = condition, y = value, fill = type), position = position_dodge(preserve = 'single'), stat = "identity", width = 0.6) +
  scale_x_discrete(labels = c("New Moon High Cover", "25-50% Visible Moon High Cover", "50-75% Visible Moon High Cover", "Full Moon High Cover", "New Moon Low Cover", "25-50% Visible Moon Low Cover", "50-75% Visible Moon Low Cover", "Full Moon Low Cover")) +
  xlab("Environmental Conditions") +
  ylab("Number of Fledglings") +
  labs(fill = "Legend") +
  scale_fill_manual(values = c("black", "grey")) +
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), axis.text.x = element_text(angle = 60, hjust = 1))
dev.off()
```

```{r Cloud Cover Chi-squared}
#Categorize cloud cover
chick <- chick %>%
  mutate(CloudCover = as.numeric(CloudCover)) %>%
  mutate(Cloud_binned = ifelse(CloudCover < 25, "first", ifelse(CloudCover < 50, "second", ifelse(CloudCover > 74, "fourth", "third"))))

#Calculate observed number of fledglings in each category
summary(as.factor(chick$Cloud_binned))
fledge_prop3 <- summary(as.factor(chick$Cloud_binned))

#Calculate expected proportion of fledglings in each category
cloud_lesp_range <- cloud_lesp_range %>% 
  mutate(CloudCover = as.numeric(CloudCover)) %>%
  mutate(new_bin = cut(CloudCover, breaks = 4, right = F))
summary(as.factor(cloud_lesp_range$new_bin))

#Chi-squared test
chisq.test(fledge_prop3, p = c(46/372, 163/372, 61/372, 102/372))

####FigureS4####
cloud_plot <- as.data.frame(table(cloud_lesp_range$CloudCover)) %>%
  left_join(as.data.frame(table(chick$CloudCover)), by = "Var1") %>%
  rename(CloudCover = Var1, Expected = Freq.x, Observed = Freq.y) %>%
  replace(is.na(.), 0) %>%
  mutate(CloudCover = as.numeric(CloudCover), Expected = as.numeric(Expected))

jpeg(filename = "figures/FigureS4_CloudChi.jpeg", units = "cm", res = 300, width = 15, height = 10)
ggplot(data = cloud_plot) +
  ylab("Percent of Birds") +
  xlab("Cloud Cover (%)") +
  geom_smooth(aes(x = CloudCover, y = (Expected/sum(Expected))*100), method = NULL, colour = "red", linetype = "dashed", linewidth = 1, se = F) +
  geom_smooth(aes(x = CloudCover, y = (Observed/sum(Observed))*100), method = NULL, colour = "black", linetype = "solid", se = F) +
  theme_classic()
dev.off()
```

#Old Code
```{r Lunar by Year}
#Binned figures by year
moon_binned17 <- moon_lesp_range %>%
  filter(Date < "2018-01-01") %>%
  mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))
moon_binned17 <- as.data.frame(summary(moon_binned17$new_bin))
fledge_binned17 <- chick %>%
  filter(Date < "2018-01-01") %>%
  mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))
fledge_binned17 <- as.data.frame(summary(fledge_binned17$new_bin))
newdf17 <- as.data.frame(cbind((seq(1:100)-1), moon_binned17/62, fledge_binned17/30))
names(newdf17) <- c("Phase", "Moon", "Chick")

p17 <- ggplot(data = newdf17)+
  xlab("Moon Illumination (%)")+
  ylab("Proportion")+
  ggtitle("2017")+
  geom_smooth(aes(x = Phase, y = Chick), linewidth = 1, colour = "black", se = F) +
  geom_smooth(aes(x = Phase, y = Moon), linetype = "dashed", linewidth = 1, colour = "red", se = F) +
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), legend.position = "none")

moon_binned18 <- moon_lesp_range %>%
  filter(Date < "2019-01-01") %>%
  filter(Date > "2018-01-01") %>%
  mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))
moon_binned18 <- as.data.frame(summary(moon_binned18$new_bin))
fledge_binned18 <- chick %>%
  filter(Date < "2019-01-01") %>%
  filter(Date > "2018-01-01") %>%
  mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))
fledge_binned18 <- as.data.frame(summary(fledge_binned18$new_bin))
newdf18 <- as.data.frame(cbind((seq(1:100)-1), moon_binned18/62, fledge_binned18/41))
names(newdf18) <- c("Phase", "Moon", "Chick")

p18 <- ggplot(data = newdf18)+
  xlab("Moon Illumination (%)")+
  ylab("Proportion")+
  ggtitle("2018")+
  geom_smooth(aes(x = Phase, y = Chick), linewidth = 1, colour = "black", se = F) +
  geom_smooth(aes(x = Phase, y = Moon), linetype = "dashed", linewidth = 1, colour = "red", se = F) +
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), legend.position = "none")

moon_binned21 <- moon_lesp_range %>%
  filter(Date < "2022-01-01") %>%
  filter(Date > "2021-01-01") %>%
  mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))
moon_binned21 <- as.data.frame(summary(moon_binned21$new_bin))
fledge_binned21 <- chick %>%
  filter(Date < "2022-01-01") %>%
  filter(Date > "2021-01-01") %>%
  mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))
fledge_binned21 <- as.data.frame(summary(fledge_binned21$new_bin))
newdf21 <- as.data.frame(cbind((seq(1:100)-1), moon_binned21/62, fledge_binned21/9))
names(newdf21) <- c("Phase", "Moon", "Chick")

p21 <- ggplot(data = newdf21)+
  xlab("Moon Illumination (%)")+
  ylab("Proportion")+
  ggtitle("2021")+
  geom_smooth(aes(x = Phase, y = Chick), linewidth = 1, colour = "black", se = F) +
  geom_smooth(aes(x = Phase, y = Moon), linetype = "dashed", linewidth = 1, colour = "red", se = F) +
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), legend.position = "none")

moon_binned22 <- moon_lesp_range %>%
  filter(Date > "2022-01-01") %>%
  mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))
moon_binned22 <- as.data.frame(summary(moon_binned22$new_bin))
fledge_binned22 <- chick %>%
  filter(Date > "2022-01-01") %>%
  mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))
fledge_binned22 <- as.data.frame(summary(fledge_binned22$new_bin))
newdf22 <- as.data.frame(cbind((seq(1:100)-1), moon_binned22/62, fledge_binned22/40))
names(newdf22) <- c("Phase", "Moon", "Chick")

p22 <- ggplot(data = newdf22)+
  xlab("Moon Illumination (%)")+
  ylab("Proportion")+
  ggtitle("2022")+
  geom_smooth(aes(x = Phase, y = Chick), linewidth = 1, colour = "black", se = F) +
  geom_smooth(aes(x = Phase, y = Moon), linetype = "dashed", linewidth = 1, colour = "red", se = F) +
  theme(panel.background = element_rect(fill = 'white', colour = 'black'), legend.position = "none")

jpeg(filename = "figures/FigureS6_LunarbyYear.jpeg", units = "cm", res = 300, width = 15, height = 12)
p17 + p18 + p21 + p22
dev.off()
```

```{r Resampling}
z <- as.data.frame(t(replicate(10000, ks.test(sample(moondates$moonlightModel, size = 1000, replace = FALSE), chick$moonlightModel)))) %>%
  mutate(p.value = as.numeric(p.value)) %>%
  mutate(statistic = as.character(statistic)) %>%
  mutate(statistic = gsub("[()]", "", statistic)) %>%
  mutate(statistic = gsub("cD = ", "", statistic)) %>%
  mutate(statistic = as.numeric(statistic))

hist(z$statistic)
summary(z$statistic)

hist(z$p.value)
summary(z$p.value)
```

```{r Moon analysis with moonlit package}
#not sure how to make the breaks in illumination
moondates_prop <- moondates %>%
  mutate(IlluminationCat = as.factor(ifelse(moonlightModel == 0, "A", ifelse(moonlightModel < 0.05, "B", ifelse(moonlightModel < 0.1, "C", "D"))))) %>%
  select(IlluminationCat)
chick_prop <- chick %>%
  mutate(IlluminationCat = as.factor(ifelse(moonlightModel == 0, "A", ifelse(moonlightModel < 0.05, "B", ifelse(moonlightModel < 0.1, "C", "D"))))) %>%
  select(IlluminationCat)

table(chick_prop$IlluminationCat)
table(moondates_prop$IlluminationCat)

chisq.test(x = c(64/120, 32/120, 16/120, 8/120), p = c(72484/147577, 33903/147577, 10637/147577, 30553/147577))
```

```{r Moon Phase Chi}
#Look at the distribution of chicks that fledged among the phases
fledge_prop <- summary(chick$Phase)

#the moon phases do not occur equally and the months are an arbitrary human invention - crop the moon dataset to the range of fledge dates for LESP
moon$yDate <- yday(moon$Date)
moon_lesp_range <- moon %>% filter(yDate < 318) %>%
  filter(yDate > 255)

#Chi-squared test
summary(as.factor(moon_lesp_range$Phase))
chisq.test(fledge_prop, p = c(113/372, 135/372, 61/372, 63/372))

#Post-hoc tests
prop.test(x = 34, n = 120, p = 113/372, alternative="two.sided") #First quarter
prop.test(x = 10, n = 120, p = 61/372, alternative="two.sided")  #Second quarter
prop.test(x = 32, n = 120, p = 63/372, alternative="two.sided")  #Third quarter
prop.test(x = 44, n = 120, p = 135/372, alternative="two.sided") #Fourth quarter

```

```{r Fledging Moon and Strandings Figure}
#Create and clean up the strandings dataset
#Want to get rid of days that had the lights on because this inflates the number of stranded birds
strand <- read.csv("data/Fishplant_2022_Feb_27_2023_SG.csv") %>%
  mutate(Date = as.POSIXlt(Date, format = "%m-%d-%Y")) %>%
  mutate(Year = Date$year + 1900) %>%
  filter(Year > 2018) %>%
  filter(Database %like% "Sherry's Data") %>%
  mutate(Stranded = as.numeric(Total_LESP)) %>%
  mutate(Lunar = as.integer(round(Lunar))) %>%
  dplyr::select(-(Plant_Lights_on.off:Number.of.Boxes)) %>%
  dplyr::select(-(Total_LESP:Database)) %>%
  drop_na() %>%
  filter(Stranded < 100)
  
boxplot(strand$Stranded)

moon_lesp_range <- moon_lesp_range %>% mutate(new_bin = cut(Moon_Illumination, breaks = 100, right = F))

moon_new <- as.data.frame(table(moon_lesp_range$new_bin))

chick_strand <- as.data.frame(table(as.integer(round(chick$Moon_Illumination)))) %>%
  rename(Fledged = Freq, Lunar = Var1) %>%
  mutate(Lunar = as.integer(as.character(Lunar))) %>%
  full_join(summaryBy(Stranded ~ Lunar, data = na.omit(strand), FUN = sum)) %>%
  mutate(Fledged = coalesce(Fledged, 0)) %>%
  mutate(Stranded.sum = coalesce(Stranded.sum, 0)) %>%
  add_row(Lunar = 22, Fledged = 0, Stranded.sum = 0) %>%
  add_row(Lunar = 60, Fledged = 0, Stranded.sum = 0) %>%
  arrange(Lunar) %>%
  mutate(Moon = moon_new$Freq)

plot(chick_strand$Stranded ~ chick_strand$Lunar, pch = 16)
plot(chick_strand$Fledged ~ chick_strand$Lunar, pch = 16)

phase_strand <- ggplot(data = chick_strand) +
  scale_y_continuous("Proportion of Chicks", labels = function(x)x/100) +
  coord_cartesian(xlim = c(0, 100), ylim = c(0, 3), expand = TRUE) +
  xlim(0, 100) +
  xlab("Moon Phase") +
  geom_smooth(aes(x = Lunar, y = (Moon/sum(Moon))*100), method = NULL, colour = "grey", linetype = "solid", linewidth = 1, se = F) +
  geom_smooth(aes(x = Lunar, y = (Fledged/sum(Fledged))*100), method = NULL, colour = "black", linetype = "solid", se = F) +
  geom_smooth(aes(x = Lunar, y = (Stranded.sum/sum(Stranded.sum))*100), method = NULL, colour = "red", linetype = "dashed", se = F) +
  theme_classic()
```